name: flutter_tutorials
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.1
  firebase_core: ^1.10.6
  firebase_auth: ^3.3.8
  google_sign_in: ^5.2.1
  google_maps_flutter: ^2.2.6
  flutter_dotenv: ^5.0.2
  sliding_up_panel: ^2.0.0+1
  contacts_service: ^0.6.1
  permission_handler: ^10.2.0
  multi_select_flutter: ^4.1.3
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/
    - assets/
    - assets/images/